---
- name: "AWS - Install docker"
  hosts: lab-servers
  tasks:
    - name: deploy nginx docker container
      docker_container:
        image: nginx:stable
        name: nginx
        state: started
        auto_remove: true
        ports:
          - "8181:80"
