---
- name: "ansible docker deployment"
  hosts: slave
  become: true
  tasks:
    - name: "Install pip"
      apt: 
        name: "python3-pip"
        state: present
            
    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: deploy nginx docker container
      docker_container:
        image: nginx:stable
        name: nginx
        state: started
        auto_remove: true
        ports:
          - "8181:80"

# apt install python3-pip
# pip3 install docker          
