---
- name: "ansible docker deployment"
  hosts: slave
  become: true
  tasks:
    - name: python3-pip install
      apt: 
        name: "python3-pip"
        state: present
            
    - name: pip docker
      pip:
        name: docker

    - name: deploy war container
      docker_container:
        image: jagrut13/e-igp-1
        name: ansible-e-igp-1
        state: started
        recreate: yes
        ports:
          - "9999:8080"

# apt install python3-pip
# pip3 install docker
# ansible-playbook  -i hosts ansible-docker-deployment.yaml  -b
