apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-igp-1
  labels:
    app: e-igp-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: e-igp-1
  template:
    metadata:
      labels:
        app: e-igp-1
    spec:
      containers:
      - name: e-igp-1
        image: jagrut13/e-igp-1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: e-igp-1
  labels:
    app: e-igp-1
spec:
  selector:
    app: e-igp-1

  type: NodePort
  ports:
  - nodePort: 31001
    port: 8080
    targetPort: 8080
